Caelum: Caelum::CloudSystem Class Reference
Caelum::CloudSystem Class Reference
A cloud system is implemented by a number of cloud layers.
#include <CloudSystem.h>
Public Types
typedef std::vector
< FlatCloudLayer * > LayerVector
Public Member Functions
CloudSystem (Ogre::SceneManager *sceneMgr, Ogre::SceneNode *cloudRoot)
LayerVector & getLayerVector ()
Direct access to the layer vector.
void clearLayers ()
Clears all cloud layers.
FlatCloudLayer * createLayer ()
Create a new cloud layer with default settings at height 0.
FlatCloudLayer * createLayerAtHeight (Ogre::Real height)
Create a new cloud layer with default settings at a certain height.
void addLayer (FlatCloudLayer *layer)
Add new layer. Takes ownership of the layer.
FlatCloudLayer * getLayer (int index)
Get a pointer to a certain layer.
int getLayerCount ()
Get the total number of layers.
void update (Ogre::Real timePassed, const Ogre::Vector3 &sunDirection, const Ogre::ColourValue &sunLightColour, const Ogre::ColourValue &fogColour, const Ogre::ColourValue &sunSphereColour)
Update function called every frame from high above.
virtual void forceLayerQueryFlags (uint flags)
Similar to.
virtual void forceLayerVisibilityFlags (uint flags)
Similar to.
Detailed Description
A cloud system is implemented by a number of cloud layers.
Different cloud layers could implement different kinds of clouds (cirrus, stratus).
Definition at line 31 of file CloudSystem.h.
Member Function Documentation
FlatCloudLayer * Caelum::CloudSystem::createLayer ()
Create a new cloud layer with default settings at height 0.
Returns:
pointer to the new layer.
Definition at line 44 of file CloudSystem.cpp.
Referenced by createLayerAtHeight().
FlatCloudLayer * Caelum::CloudSystem::createLayerAtHeight (Ogre::Real height)
Create a new cloud layer with default settings at a certain height.
Returns:
pointer to the new layer.
Definition at line 37 of file CloudSystem.cpp.
References createLayer(), and Caelum::FlatCloudLayer::setHeight().
void Caelum::CloudSystem::forceLayerQueryFlags (uint flags) [virtual]
Similar to.
See also:
CaelumSystem::forceSubcomponentQueryFlags.
Definition at line 84 of file CloudSystem.cpp.
Referenced by Caelum::CaelumSystem::forceSubcomponentQueryFlags().
void Caelum::CloudSystem::forceLayerVisibilityFlags (uint flags) [virtual]
Similar to.
See also:
CaelumSystem::forceSubcomponentVisibilityFlags.
Definition at line 90 of file CloudSystem.cpp.
Referenced by Caelum::CaelumSystem::forceSubcomponentVisibilityFlags().
The documentation for this class was generated from the following files:
main/include/CloudSystem.h
main/src/CloudSystem.cpp