Caelum: Caelum::SkyDome Class Reference
Caelum::SkyDome Class Reference
A sky dome element.
#include <SkyDome.h>
Classes
struct Params
Public Member Functions
SkyDome (Ogre::SceneManager *sceneMgr, Ogre::SceneNode *caelumRootNode)
Constructor This will setup some nice defaults.
virtual ~SkyDome ()
Destructor.
void setSunDirection (const Ogre::Vector3 &dir)
Sets the sun direction.
void setHazeColour (const Ogre::ColourValue &hazeColour)
Explicit haze colour.
void setSkyGradientsImage (const Ogre::String &gradients)
Set the sky color gradients image.
void setAtmosphereDepthImage (const Ogre::String &gradients)
Set the atmosphere depthh gradient image.
void setHazeEnabled (bool value)
Enable or disable skydome haze.
bool getHazeEnabled () const
If skydome haze is enabled.
void setQueryFlags (uint flags)
uint getQueryFlags () const
void setVisibilityFlags (uint flags)
uint getVisibilityFlags () const
virtual void notifyCameraChanged (Ogre::Camera *cam)
Handle camera change.
Protected Member Functions
virtual void setFarRadius (Ogre::Real radius)
Handle far radius.
Detailed Description
A sky dome element.
Definition at line 33 of file SkyDome.h.
Constructor & Destructor Documentation
Caelum::SkyDome::SkyDome (Ogre::SceneManager * sceneMgr, Ogre::SceneNode * caelumRootNode)
Constructor This will setup some nice defaults.
Parameters:
sceneMgr The scene manager where this sky dome will be created.
Definition at line 31 of file SkyDome.cpp.
References Caelum::InternalUtilities::checkLoadMaterialClone(), Caelum::InternalUtilities::generateSphericDome(), Caelum::InternalUtilities::pointerToString(), Caelum::PrivatePtr< PointedT, TraitsT >::reset(), and setHazeEnabled().
Member Function Documentation
void Caelum::SkyDome::setSunDirection (const Ogre::Vector3 & dir)
Sets the sun direction.
Parameters:
dir The sun light direction.
Definition at line 70 of file SkyDome.cpp.
Referenced by Caelum::CaelumSystem::updateSubcomponents().
void Caelum::SkyDome::setHazeEnabled (bool value)
Enable or disable skydome haze.
This makes the sky darker. By default haze is disabled.
Definition at line 122 of file SkyDome.cpp.
Referenced by SkyDome().
The documentation for this class was generated from the following files:
main/include/SkyDome.h
main/src/SkyDome.cpp